/**
 * Instacart Deep Linking Integration
 * Enables ordering ingredients directly from Instacart
 */

import { Linking, Platform, Alert } from "react-native";

const INSTACART_BASE_URL = "https://www.instacart.com";
const INSTACART_APP_SCHEME = "instacart://";

interface GroceryItem {
  name: string;
  quantity?: number;
  unit?: string;
}

/**
 * Check if Instacart app is installed
 */
export async function isInstacartInstalled(): Promise<boolean> {
  if (Platform.OS === "ios") {
    return await Linking.canOpenURL(INSTACART_APP_SCHEME);
  }
  // Android - just try to open, it will fallback to web
  return true;
}

/**
 * Format ingredients for Instacart search
 */
function formatIngredientForSearch(item: GroceryItem): string {
  let searchTerm = item.name;
  // Remove common measurement words that don't help search
  searchTerm = searchTerm.replace(
    /\b(to taste|as needed|for garnish|optional|divided|packed)\b/gi,
    ""
  );
  // Clean up extra spaces
  searchTerm = searchTerm.replace(/\s+/g, " ").trim();
  return encodeURIComponent(searchTerm);
}

/**
 * Generate Instacart search URL for a single ingredient
 */
export function getInstacartSearchUrl(ingredient: string): string {
  const encoded = encodeURIComponent(ingredient);
  return `${INSTACART_BASE_URL}/store/search/${encoded}`;
}

/**
 * Generate Instacart URL with multiple items (shopping list)
 * Note: Instacart doesn't support bulk add via URL, so we search for first item
 */
export function getInstacartShoppingUrl(items: GroceryItem[]): string {
  if (items.length === 0) {
    return INSTACART_BASE_URL;
  }
  
  // Search for the first item - user can add more from there
  const firstItem = formatIngredientForSearch(items[0]);
  return `${INSTACART_BASE_URL}/store/search/${firstItem}`;
}

/**
 * Open Instacart app or website with ingredient search
 */
export async function openInstacartWithIngredient(
  ingredient: string
): Promise<boolean> {
  try {
    const url = getInstacartSearchUrl(ingredient);
    const supported = await Linking.canOpenURL(url);
    
    if (supported) {
      await Linking.openURL(url);
      return true;
    } else {
      console.warn("[Instacart] Cannot open URL:", url);
      return false;
    }
  } catch (error) {
    console.error("[Instacart] Error opening URL:", error);
    return false;
  }
}

/**
 * Open Instacart with a shopping list
 */
export async function openInstacartWithShoppingList(
  items: GroceryItem[]
): Promise<boolean> {
  if (items.length === 0) {
    Alert.alert(
      "No Items",
      "Add some ingredients to your shopping list first."
    );
    return false;
  }

  try {
    const url = getInstacartShoppingUrl(items);
    const supported = await Linking.canOpenURL(url);
    
    if (supported) {
      await Linking.openURL(url);
      return true;
    } else {
      // Fallback to web
      await Linking.openURL(INSTACART_BASE_URL);
      return true;
    }
  } catch (error) {
    console.error("[Instacart] Error opening shopping list:", error);
    Alert.alert(
      "Error",
      "Could not open Instacart. Please try again."
    );
    return false;
  }
}

/**
 * Show Instacart order confirmation dialog
 */
export function showInstacartPrompt(
  items: GroceryItem[],
  onConfirm: () => void
): void {
  const itemCount = items.length;
  const itemText = itemCount === 1 ? "1 ingredient" : `${itemCount} ingredients`;
  
  Alert.alert(
    "Order from Instacart",
    `Send ${itemText} to Instacart for delivery?\n\nYou'll be redirected to the Instacart app or website to complete your order.`,
    [
      {
        text: "Cancel",
        style: "cancel",
      },
      {
        text: "Order Now",
        onPress: onConfirm,
        style: "default",
      },
    ]
  );
}

/**
 * Generate a formatted shopping list text for sharing
 */
export function formatShoppingListForShare(
  items: GroceryItem[],
  recipeName?: string
): string {
  let text = recipeName
    ? `Shopping List for "${recipeName}"\n\n`
    : "Shopping List\n\n";

  items.forEach((item, index) => {
    let line = `${index + 1}. ${item.name}`;
    if (item.quantity && item.unit) {
      line = `${index + 1}. ${item.quantity} ${item.unit} ${item.name}`;
    } else if (item.quantity) {
      line = `${index + 1}. ${item.quantity}x ${item.name}`;
    }
    text += line + "\n";
  });

  text += "\n---\nGenerated by Sous Chef";
  return text;
}

/**
 * Check if grocery delivery is available (simplified check)
 */
export async function isGroceryDeliveryAvailable(): Promise<boolean> {
  // In a production app, you might check:
  // 1. User's location for delivery availability
  // 2. Instacart API for store availability
  // For now, we assume it's always available
  return true;
}

export default {
  isInstacartInstalled,
  openInstacartWithIngredient,
  openInstacartWithShoppingList,
  showInstacartPrompt,
  getInstacartSearchUrl,
  getInstacartShoppingUrl,
  formatShoppingListForShare,
  isGroceryDeliveryAvailable,
};
